### ISSUE TITLE
Not working with latest October build 458

### ISSUE THREAD

**Issue by amdad** [aspendigital/oc-resizer-plugin#4]
Hey thanks for awesome plug. Unfortunately after update to latest build it throws issue like this: 

**Access level to AspenDigital\Resizer\Models\ExtendedFile::getThumbFilename() must be public (as in class October\Rain\Database\Attach\File)**

**Comment by jimcottrell** [comment]
@amdad Thanks for pointing that out. I haven't updated any projects to build 458 yet so I hadn't seen that error pop up. I've pushed a fix.

Thanks again!

**Comment by amdad** [comment]
![image](https://user-images.githubusercontent.com/10062429/64456419-71b61e80-d0f0-11e9-9809-42139651b310.png)
